### ISSUE TITLE
Zero scores for Primary Care Access and counts

### ISSUE THREAD

**Issue by dads2busy** [uva-bi-sdad/community#4]
both access scores and counts for primary care access are all zeros. Colors are still being shown on map.

**Comment by miserman** [comment]
5776b024cb16f848fa714a8e3d24de126168f1df should fix an issue with the rank table not updating when the variable changes but other aspects of the view stay the same, which lead to some mismatches with other outputs. Otherwise, I think this and #5 and #6 are just due to the small values rounding to 0 when formatted for display.

**Comment by cesarmontalvo** [comment]
yes, I think it is the rounding to 0

**Comment by miserman** [comment]
The originals going into this, #5, and #6 are rescaled.
