### ISSUE TITLE
Box Plot labels

### ISSUE THREAD

**Issue by dads2busy** [uva-bi-sdad/community#7]
Box plot label shows min 14.0598, actual min is 10.somthing
<img width="921" alt="Screen Shot 2022-04-20 at 2 00 44 PM" src="https://user-images.githubusercontent.com/1839094/164297225-08b96635-9c11-4bfc-a6ce-d2f80cc5e795.png">

**Comment by miserman** [comment]
The boxplot labels do not currently change between min/max and +/- 1.5 * IRQ (which is what's being shown there). I don't think there's a way to change those labels through Plotly, so they'll probably need to be rewritten with some code whenever updated.

**Comment by dads2busy** [comment]
Take a look under the section "Styling Outliers" on this page:
https://plotly.com/r/box-plots/

the whiskers are called upper and lower fence, and there are separate min and max values. It's not clear to me how the option is selected but I see it in a couple of the examples on this page.

**Comment by miserman** [comment]
Those other labels show up when points are being displayed as part of the box plots, but we are drawing the boxes and points separately (allowing for the summary statistics to be calculated outside of Plotly, boxes to be toggled independently, and a different number of point traces to be displayed). I don't think there's a way to set the text of the label directly through Plotly.

**Comment by dads2busy** [comment]
gotcha
________________________________

**Comment by miserman** [comment]
I tried changing the text of the labels directly, but they seem to be recreated on mouse move. I could only consistently change them after Plotly had updated them with a timeout after mouse move, which resulted in a flicker between the original and updated labels with any mouse movement.

I think that means the labels will have to be recreated outside of the box plot trace, unless there's a setting or better hook I'm missing, or we can find a way to replace the original label components or something.

0e39ab162c215b549d276765b8972578de9609fc adds some raw data (just the min and max in each year) to each trace, which makes the min/max and lower/upper fence labels show up, but only if the min/max is outside of the whisker range -- otherwise, the whiskers are still labeled as min/max. I'm not sure if that's worse than just always showing min/max.

**Comment by miserman** [comment]
a97b9fff9bc0a1fcc0124b6964a86ce074565ce0 disables box plot labels.
